/* action types */
const POSTS_REQUESTED = 'POSTS_REQUESTED';
const POSTS_LOADED = 'POSTS_LOADED';
const POSTS_REJECTED = 'POSTS_REJECTED';
const ADD_POST = 'ADD_POST';
const POST_LIKED = 'POST_LIKED';
const FRIENDS_REQUESTED = 'FRIENDS_REQUESTED';
const FRIENDS_LOADED = 'FRIENDS_LOADED';
const FRIENDS_REJECTED = 'FRIENDS_REJECTED';

export { 
   POSTS_REQUESTED, 
   POSTS_LOADED, 
   POSTS_REJECTED, 
   ADD_POST, 
   POST_LIKED, 
   FRIENDS_REQUESTED,
   FRIENDS_LOADED,
   FRIENDS_REJECTED
};