/* action types */
const POSTS_REQUESTED = 'POSTS_REQUESTED';
const POSTS_LOADED = 'POSTS_LOADED';
const POSTS_REJECTED = 'POSTS_REJECTED';
const ADD_POST = 'ADD_POST';

export { POSTS_REQUESTED, POSTS_LOADED, POSTS_REJECTED, ADD_POST };