/* action types */
const ADD_POST = 'ADD_POST';
const AD_ADD = 'AD_ADD';
const ADS_LOADING = 'ADS_LOADING';
const ADS_REJECTED = 'ADS_REJECTED';
const FRIENDS_REQUESTED = 'FRIENDS_REQUESTED';
const FRIENDS_LOADED = 'FRIENDS_LOADED';
const FRIENDS_REJECTED = 'FRIENDS_REJECTED';
const POSTS_REQUESTED = 'POSTS_REQUESTED';
const POSTS_LOADED = 'POSTS_LOADED';
const POSTS_REJECTED = 'POSTS_REJECTED';
const POST_LIKED = 'POST_LIKED';

export { 
   ADD_POST,
	AD_ADD,
	ADS_LOADING,
	ADS_REJECTED,
	FRIENDS_REQUESTED,
	FRIENDS_LOADED,
	FRIENDS_REJECTED,
	POSTS_REQUESTED,
	POSTS_LOADED,
	POSTS_REJECTED,
	POST_LIKED
};